services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    image: nazeef-portfolio:latest
    container_name: nazeef-portfolio-container
    ports:
      - "8080:80"
    restart: unless-stopped
